### PR TITLE
Add function on iterable benchmark

### PR DESCRIPTION
**Pull request by Herklos**
Lists size = 5000
Timy executed (with_map) for 1000 times in 0.000191 seconds
Timy best time was 0.000000 seconds
Timy executed (with_comprehension) for 1000 times in 2.411777 seconds
Timy best time was 0.002230 seconds

### CODE REVIEW

**Review by GuillaumeDSM — APPROVED** [review]
😮

**Review by GuillaumeDSM — CHANGES_REQUESTED** [review]
Actually map returns a generator, not a list, it's a bit different. We can use it some times but not all the time we use a list

**Comment by Herklos** [comment]
> Actually map returns a generator, not a list, it's a bit different. We can use it some times but not all the time we use a list

You can just do `list(map(X))` if you need a list.

**Comment by GuillaumeDSM** [comment]
> > Actually map returns a generator, not a list, it's a bit different. We can use it some times but not all the time we use a list
> 
> You can just do `list(map(X))` if you need a list.

Right, and it should be added in the benchmark to compare it with a comprehension list

**Review by GuillaumeDSM — APPROVED** [review]
:+1:

**Pull request merged**
